default_basic_plan_price: 9.95
default_professional_plan_price: 19.95
default_enterprise_plan_price: 49.95

default_check_price: 0.45
default_advanced_check_price: 0.95
default_domain_price: 0.45
default_record_price: 0.15
default_geodns_record_price: 0.45

default_basic_plan_every: 1
default_professional_plan_every: 1
default_enterprise_plan_every: 1
default_always_resolve_every: 1
default_domain_every: 1
default_web_cache_every: 1

default_domains_per_free_plan: 0
default_domains_per_basic_plan: 0
default_domains_per_professional_plan: 5
default_domains_per_enterprise_plan: 10

default_ars_per_free_plan: 0
default_ars_per_basic_plan: 0
default_ars_per_professional_plan: 10
default_ars_per_enterprise_plan: 30

default_records_per_free_plan: 1
default_records_per_basic_plan: 100
default_records_per_professional_plan: 20
default_records_per_enterprise_plan: 30

free_record: 2
basic_record: 2
professional_record: 6
enterprise_record: 8
